### ISSUE TITLE
Use twisted.web.client.Agent instead of twisted.web.client.getPage

### ISSUE THREAD

**Issue by exarkun** [twisted/txaws#14]
`getPage` *still* isn't deprecated!  It's amazing.  But it really should be and it probably will be.  Also `Agent` is a lot easier to interact with in tests, has certificate validation features almost by default, and is better in a bunch of other ways too.

**Comment by exarkun** [comment]
Ah, someone did this already (mistakenly looked at my forked, out-of-date version of the code when filing this).

**Comment by rodrigc** [comment]
Yes, getPage() was just recently deprecated https://github.com/twisted/twisted/pull/643 :)
