### ISSUE TITLE
Respect AWS_PROFILE environment variable

### ISSUE THREAD

**Issue by exarkun** [twisted/txaws#15]
The official AWS SDK will look at AWS_PROFILE and then look up credentials in `~/.aws`.

This is a very convenient way to operate and avoids ever putting the sensitive secret material into an environment variable where it might be exposed to an attacker.

**Comment by mithrandi** [comment]
This seems like a good idea, as long as there's still some way to bypass this, what with environment variables being global process state. I imagine being able to pass credentials in directly would still be supported though, which would meet my requirement without any further effort, but I felt like this deserved a mention anyway.

**Comment by exarkun** [comment]
Indeed.  +1 to being able to override/ignore the environment variable.  In fact, I'd prefer if AWSCredentials made you be explicit about your desire to respect them at all.  Rather than having `AWSCredentials("", "")` load values from the environment, I'd rather you have to do something like `AWSCredentials.from_environment()` (perhaps optionally accepting an environment dictionary).

**Comment by Julian** [comment]
Addressed in #54

**Comment by Julian** [comment]
Think this is closeable now.
