### ISSUE TITLE
S3 object keys are not quoted

### ISSUE THREAD

**Issue by exarkun** [twisted/txaws#20]
(At least) `S3Client.get_object` fails to quote the object key into the URL it generates for the request.  For any key with anything that's a url special character, this causes problems.

AWS maybe respond to such requests with a weird looking 505 claiming an unsupported HTTP version was requested.

**Comment by mithrandi** [comment]
This was fixed somewhere along the way. Except, it was also broken differently at the same time: signing ends up using a double-encoded path and fails.
