### ISSUE TITLE
TXAWS_INTEGRATION_* variables aren't set in a way that makes them usable

### ISSUE THREAD

**Issue by exarkun** [twisted/txaws#22]
The integration tests are failing to find these variables on travis-ci.  Not sure why.

**Comment by exarkun** [comment]
Also, travis-ci related, boto3 needs to be installed to run the cleanup code.

**Comment by mithrandi** [comment]
I can't find anything wrong except possibly the fact that we're using `env.global` but there is no build matrix, only a single build; the docs say that global variables are "inserted into each matrix row", so perhaps our current configuration counts as zero rows? At least it should be possible to experiment with a PR from the twisted/txaws repo.

**Comment by exarkun** [comment]
After about a day, the variables started being set.  I have no idea why it wasn't working or why it started working.  It is, however, working.
