### ISSUE TITLE
Implement Route 53 support

### ISSUE THREAD

**Issue by mithrandi** [twisted/txaws#3]
I'll be needing this for mithrandi/txacme#32 so it might as well go in txaws instead of fragmenting the ecosystem further.

**Comment by exarkun** [comment]
I think I'm going to need this soon.  Still on your to-do list, @mithrandi ?

**Comment by exarkun** [comment]
Specifically, I think I'll need to list and modify record sets (*much* less than the full Route 53 API).

**Comment by mithrandi** [comment]
It is still on my radar, so to speak, but I probably won't get around to do anything in the next month or two.
