### ISSUE TITLE
Grant mithrandi access to the project

### ISSUE THREAD

**Issue by mithrandi** [twisted/txaws#4]
As one of the original developers / maintainers (although I haven't been active for quite a while), I'd like to request maintainer access for the GitHub repository :)

Perhaps we should move this to a txaws org? Although it doesn't matter much for now.

**Comment by oubiwann** [comment]
I'd like to add you and @exarkun both ... a new org is an interesting possibility. What about the Twisted org?

**Comment by oubiwann** [comment]
Oh, and massive apologies -- I didn't see this until tonight :-(

**Comment by oubiwann** [comment]
Ah, looks like in August @graingert invited me to the newly-created txaws org ... is there where you guys would like the project to be transferred?

**Comment by mithrandi** [comment]
Hmm, I forgot (or maybe never noticed) that there was a txaws org (I see I was invited too, but only as a member). @twisted seems like a reasonable home; both @exarkun and myself are org admins, as well as a whole bunch of people which would give us a bit more administrative continuity. I think moving there would be an implicit commitment to [Twisted's compatibility policy](https://twistedmatrix.com/documents/current/core/development/policy/compatibility-policy.html), but I don't think that should be objectionable (in fact, I'd like to propose explicitly committing to it).

It looks like you're currently the only one with access to the PyPI record as well, so adding a few more people there would probably be a good idea.

Finally, there seems to have been a tiny bit of activity [over at Launchpad](http://bazaar.launchpad.net/~txaws-dev/txaws/trunk/changes) that we should integrate here; and we should probably reach out to those folks as well to get them to join us over here at GitHub.

**Comment by mithrandi** [comment]
I polled a few other @twisted admins informally and didn't get any objections; if you initiate the transfer request from your side I can approve it :)

**Comment by oubiwann** [comment]
Okay, @twisted it is.

Here's what I've done:
 * applied all the missing changes from launchpad (oh, don't ask ... it was a nightmare)
 * updated the history for my commits to point to valid email addresses (many of my commits will have different ids now)

Will transfer ownership next ...

**Comment by oubiwann** [comment]
I've attempted a transfer, but got an error message
```
You don’t have the permission to create repositories on twisted 
```
I'm not sure if there's anything in the queue, but I'm guessing not? I used to be on some of the teams for Twisted (GitHub) -- if you want to add me for this, I'll drop the perms as soon as the transfer goes through ...

**Comment by mithrandi** [comment]
Ah, I missed this bit in the docs: "Users must have admin or owner permissions within the receiving organization before they can transfer a repository that they individually own."

**Comment by oubiwann** [comment]
Yup, just read that too -- another option is I can transfer it to you, you accept, and then you can do as you see fit :-)

**Comment by oubiwann** [comment]
Ah, nope -- you already have a fork. Well, I tried ;-)

**Comment by mithrandi** [comment]
I invited you as a regular member of @twisted and temporarily enabled the setting that allows regular members to create repositories; I think this should be enough to allow the transfer, can you check?

**Comment by oubiwann** [comment]
Nope, still same error.

**Comment by mithrandi** [comment]
I think you need to accept the invite first, GitHub tells me it's still "pending".

**Comment by oubiwann** [comment]
Doh.

Okay, done!

What is your PyPI user name? mithrandi? I'll add you. I'm guessing @exarkun's is the same as he is here ...

**Comment by mithrandi** [comment]
Yes to both of those.

**Comment by oubiwann** [comment]
Done! You should be all set now :-)

**Comment by mithrandi** [comment]
Closing, since it all looks good to me; thanks!
